# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/artem/For_BMSTU/Veselov-CPP-Labs-2025

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/artem/For_BMSTU/Veselov-CPP-Labs-2025

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/For_BMSTU/Veselov-CPP-Labs-2025/CMakeFiles /home/artem/For_BMSTU/Veselov-CPP-Labs-2025//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/For_BMSTU/Veselov-CPP-Labs-2025/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lab-4

# Build rule for target.
lab-4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab-4
.PHONY : lab-4

# fast build rule for target.
lab-4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab-4.dir/build.make CMakeFiles/lab-4.dir/build
.PHONY : lab-4/fast

#=============================================================================
# Target rules for targets named clang-format

# Build rule for target.
clang-format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clang-format
.PHONY : clang-format

# fast build rule for target.
clang-format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clang-format.dir/build.make CMakeFiles/clang-format.dir/build
.PHONY : clang-format/fast

lab_4/main.o: lab_4/main.cpp.o
.PHONY : lab_4/main.o

# target to build an object file
lab_4/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab-4.dir/build.make CMakeFiles/lab-4.dir/lab_4/main.cpp.o
.PHONY : lab_4/main.cpp.o

lab_4/main.i: lab_4/main.cpp.i
.PHONY : lab_4/main.i

# target to preprocess a source file
lab_4/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab-4.dir/build.make CMakeFiles/lab-4.dir/lab_4/main.cpp.i
.PHONY : lab_4/main.cpp.i

lab_4/main.s: lab_4/main.cpp.s
.PHONY : lab_4/main.s

# target to generate assembly for a file
lab_4/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab-4.dir/build.make CMakeFiles/lab-4.dir/lab_4/main.cpp.s
.PHONY : lab_4/main.cpp.s

lab_4/sorting.o: lab_4/sorting.cpp.o
.PHONY : lab_4/sorting.o

# target to build an object file
lab_4/sorting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab-4.dir/build.make CMakeFiles/lab-4.dir/lab_4/sorting.cpp.o
.PHONY : lab_4/sorting.cpp.o

lab_4/sorting.i: lab_4/sorting.cpp.i
.PHONY : lab_4/sorting.i

# target to preprocess a source file
lab_4/sorting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab-4.dir/build.make CMakeFiles/lab-4.dir/lab_4/sorting.cpp.i
.PHONY : lab_4/sorting.cpp.i

lab_4/sorting.s: lab_4/sorting.cpp.s
.PHONY : lab_4/sorting.s

# target to generate assembly for a file
lab_4/sorting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab-4.dir/build.make CMakeFiles/lab-4.dir/lab_4/sorting.cpp.s
.PHONY : lab_4/sorting.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clang-format"
	@echo "... lab-4"
	@echo "... lab_4/main.o"
	@echo "... lab_4/main.i"
	@echo "... lab_4/main.s"
	@echo "... lab_4/sorting.o"
	@echo "... lab_4/sorting.i"
	@echo "... lab_4/sorting.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

